name: unit tests

on:
  pull-request:
    branches: [sll]

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Run Tests
        run: go test -cover ./...